-- Run this in the Supabase SQL editor before using Supabase-backed logins.
-- The Flask app talks to this table through the Supabase REST API.

create table if not exists public.accounts (
    id bigint generated by default as identity primary key,
    username text not null unique,
    password_hash text not null,
    is_admin boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_accounts_updated_at on public.accounts;

create trigger set_accounts_updated_at
before update on public.accounts
for each row
execute function public.set_updated_at();

create index if not exists accounts_username_idx on public.accounts (username);
