-- Run this in the Supabase SQL editor before using the app on Supabase.
-- The Flask app talks to these tables through the Supabase REST API.

create table if not exists public.accounts (
    id bigint generated by default as identity primary key,
    username text not null unique,
    password_hash text not null,
    is_admin boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_accounts_updated_at on public.accounts;

create trigger set_accounts_updated_at
before update on public.accounts
for each row
execute function public.set_updated_at();

create index if not exists accounts_username_idx on public.accounts (username);

create table if not exists public.products (
    id bigint generated by default as identity primary key,
    name text not null,
    category text not null,
    price numeric(12, 2) not null check (price >= 0),
    stock integer not null default 0 check (stock >= 0),
    description text,
    image_url text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

drop trigger if exists set_products_updated_at on public.products;

create trigger set_products_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

create index if not exists products_category_idx on public.products (category);
create index if not exists products_name_idx on public.products (name);

create table if not exists public.settings (
    id bigint generated by default as identity primary key,
    key text not null unique,
    value text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

drop trigger if exists set_settings_updated_at on public.settings;

create trigger set_settings_updated_at
before update on public.settings
for each row
execute function public.set_updated_at();

create index if not exists settings_key_idx on public.settings (key);
